# Use the official Rust image with Linux base (Debian-based)
FROM rust:latest

# Set working directory inside the container
WORKDIR /usr/src/app

# Copy the contents of server directory into container's /usr/src/myapp
# COPY ../server/ .

# # Build the project in release mode
# RUN cargo build --release