name: fin_stack_api

services:
  postgres:
    image: postgres:17
    container_name: fin_stack_db
    environment:
      POSTGRES_DB: finstack
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passw0rd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 