services:
  # PostgreSQL Database
  postgres:
    image: postgres:16
    container_name: finstack_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_DB: finstack
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # API Server
  server:
    profiles:
      - with-server
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finstack_api
    restart: always
    init: true
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://user:passw0rd@postgres:5432/finstack
      - SERVER_URL=0.0.0.0:8080
      - RUST_LOG=info
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy
  nginx:
    profiles:
      - with-server
    image: nginx:latest
    container_name: finstack_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server

networks:
  default:
    driver: bridge

volumes:
  postgres_data: 